// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClDUYmVn-m0vW1nrOMhxlv5rM3yA3TLuE',
    appId: '1:211744902089:web:307ca8984ffceaabc2f618',
    messagingSenderId: '211744902089',
    projectId: 'friendzy-app-ui',
    authDomain: 'friendzy-app-ui.firebaseapp.com',
    storageBucket: 'friendzy-app-ui.firebasestorage.app',
    measurementId: 'G-LV6XC2131D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLr9oRGTkeZpvSvpvKKM71-9ZeVjL9Y8M',
    appId: '1:211744902089:android:14f4533565eb8fcdc2f618',
    messagingSenderId: '211744902089',
    projectId: 'friendzy-app-ui',
    storageBucket: 'friendzy-app-ui.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA57xm_-dsrSTQj1mYWLYyJcNvgaZZzHvQ',
    appId: '1:211744902089:ios:593eb3cf39026489c2f618',
    messagingSenderId: '211744902089',
    projectId: 'friendzy-app-ui',
    storageBucket: 'friendzy-app-ui.firebasestorage.app',
    iosBundleId: 'com.example.friendzyUiApp',
  );
}
